In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
a = [1,2,3,4]

In [34]:
c = np.copy(a)       #deep copy

In [26]:
c

array([1, 2, 3, 4])

In [27]:
a[1]=100

In [28]:
c

array([1, 2, 3, 4])

In [29]:
a

[1, 100, 3, 4]

In [30]:
c[0] = 200

In [31]:
c

array([200,   2,   3,   4])

In [32]:
a

[1, 100, 3, 4]

In [36]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [37]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [38]:
np.fromfunction(lambda i,j : i+j ,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [65]:
w = np.fromfunction(lambda i,j : i-j ,(3,3))

In [66]:
w

array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [67]:
w.ndim

2

In [48]:
iterable = (i*i for i in range(5))

In [49]:
np.fromiter(iterable , int)

In [57]:
np.fromstring('4 5' ,sep='  '  )

array([4., 5.])

In [58]:
 np.fromstring('4,5,6,7' , sep=','  )

array([4., 5., 6., 7.])

In [59]:
l 

[1, 2, 3, 4, 5]

In [191]:
ar = np.array(l)

In [100]:
ar.ndim

1

In [91]:
a= [[[1,2,3,4],[0,1,2,3]]]
a

[[[1, 2, 3, 4], [0, 1, 2, 3]]]

In [95]:
ar3 =np.array(a)
ar3

array([[[1, 2, 3, 4],
        [0, 1, 2, 3]]])

In [96]:
ar3.ndim

3

In [97]:
ar3.shap

(1, 2, 4)

In [192]:
ar

array([1, 2, 3, 4, 5])

In [101]:
ar.shape

(5,)

In [102]:
ar3.dtype

dtype('int64')

In [103]:
ar.dtype

dtype('int64')

In [107]:
np.arange(0.1,6.1)

array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1])

In [116]:
list(np.arange(1.2,6.5,.5))

[1.2, 1.7, 2.2, 2.7, 3.2, 3.7, 4.2, 4.7, 5.2, 5.7, 6.2]

In [119]:
np.linspace(1,6,12)

array([1.        , 1.45454545, 1.90909091, 2.36363636, 2.81818182,
       3.27272727, 3.72727273, 4.18181818, 4.63636364, 5.09090909,
       5.54545455, 6.        ])

In [121]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [124]:
ar = np.zeros((3,4,3,2))

In [125]:
ar.ndim

4

In [126]:
ar

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [132]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [134]:
a=np.ones((2,4,3))

In [136]:
c = a *2

In [137]:
c

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

In [138]:
c+5

array([[[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]],

       [[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]]])

In [147]:
np.empty((5,4))

array([[ 4.65966729e-310,  0.00000000e+000,  5.65622866e+303,
        -7.52075315e-304],
       [-7.52075315e-304,  5.65622866e+303,  5.65622866e+303,
        -7.52075315e-304],
       [-7.52075315e-304,  5.65622866e+303,  5.65622866e+303,
        -7.52075315e-304],
       [-7.52075315e-304,  5.65622866e+303,  5.65622866e+303,
         8.20430627e-304],
       [ 9.11571042e-304,  9.11571042e-304, -7.52075315e-304,
        -7.52075315e-304]])

In [193]:
a =np.eye((4)) 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [196]:
import pandas as pd

In [195]:
pd.DataFrame(a)

0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0

In [194]:
np.logspace(2,5 ,7)     # finding logarith  "2,3,4,5"

array([   100.        ,    316.22776602,   1000.        ,   3162.27766017,
        10000.        ,  31622.77660168, 100000.        ])

In [154]:
np.random.randn(3,4)

array([[-0.55259668,  0.57330443, -0.31386792,  0.22216175],
       [ 0.63995393, -0.15549787,  1.62801137,  1.08747497],
       [ 0.11130034,  0.68473592, -1.56451588,  1.83121176]])

In [163]:
ar = np.random.rand(3,4)
ar

array([[0.81388773, 0.28219661, 0.7734844 , 0.29494301],
       [0.80757932, 0.18589803, 0.12406041, 0.43880134],
       [0.85837597, 0.49766137, 0.38576762, 0.90613297]])

In [164]:
import pandas as pd

In [165]:
pd.DataFrame(ar)

0         1         2         3
0  0.813888  0.282197  0.773484  0.294943
1  0.807579  0.185898  0.124060  0.438801
2  0.858376  0.497661  0.385768  0.906133

In [168]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [167]:
pd.DataFrame(a)

In [172]:
ar = np.random.rand(3,4)

array([[29, 41,  8, ..., 43, 13, 35],
       [10, 14,  5, ..., 15, 21, 40],
       [20, 40, 33, ...,  7,  9, 18],
       ...,
       [20,  7, 24, ..., 13, 20, 25],
       [26, 23,  4, ...,  4, 15,  5],
       [23, 27,  5, ..., 15, 43,  3]])

In [206]:
np.random.randint(3,4 ,(50,60))

array([[3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       ...,
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3]])

In [207]:
pd.DataFrame(np.random.randint(3,4 ,(50,60))).to_csv("text.csv")

In [208]:
ar = np.random.rand(3,4)
ar

array([[0.53947251, 0.52987153, 0.11596439, 0.30402571],
       [0.91411077, 0.68976579, 0.11087637, 0.70011258],
       [0.25024606, 0.28897492, 0.6960524 , 0.46129077]])

In [212]:
s = ar.reshape(6,2)
s

array([[0.53947251, 0.52987153],
       [0.11596439, 0.30402571],
       [0.91411077, 0.68976579],
       [0.11087637, 0.70011258],
       [0.25024606, 0.28897492],
       [0.6960524 , 0.46129077]])

In [214]:
s[0][0]

0.5394725098011095

In [224]:
s[1:4:,0]

array([0.11596439, 0.91411077, 0.11087637])

In [235]:
ar = np.random.randint(3,40 ,(4,5))
ar

array([[36, 11, 22, 38, 16],
       [20,  8, 38, 11, 35],
       [30, 30, 30, 33, 33],
       [31, 33, 12, 37,  9]])

In [236]:
ar>20   # to collect data is grater than 20

array([[ True, False,  True,  True, False],
       [False, False,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True, False]])

In [237]:
ar[ar>20]   #to collect data is grater than 20

array([36, 22, 38, 38, 35, 30, 30, 30, 33, 33, 31, 33, 37])

In [238]:
ar

array([[36, 11, 22, 38, 16],
       [20,  8, 38, 11, 35],
       [30, 30, 30, 33, 33],
       [31, 33, 12, 37,  9]])

In [240]:
ar[1:3,[2,3]]

array([[38, 11],
       [30, 33]])

In [244]:
ar[2:4,[3,4]]

array([[33, 33],
       [37,  9]])

In [246]:
ar[0][0]=100
ar

array([[100,  11,  22,  38,  16],
       [ 20,   8,  38,  11,  35],
       [ 30,  30,  30,  33,  33],
       [ 31,  33,  12,  37,   9]])

In [250]:
ar[3][4] =1000
ar

array([[ 100,   11,   22,   38,   16],
       [  20,    8,   38,   11,   35],
       [  30,   30,   30,   33,   33],
       [  31,   33,   12,   37, 1000]])

In [263]:
ar1 = np.random.randint(1,3 ,(3,3))
ar2= np.random.randint(1,3 ,(3,3))

In [264]:
ar1

array([[2, 1, 2],
       [2, 1, 1],
       [1, 1, 2]])

In [265]:
ar2

array([[1, 1, 2],
       [2, 2, 2],
       [2, 1, 1]])

In [266]:
ar1+ar2

array([[3, 2, 4],
       [4, 3, 3],
       [3, 2, 3]])

In [268]:
ar1*ar2

array([[2, 1, 4],
       [4, 2, 2],
       [2, 1, 2]])

In [270]:
ar1@ar2    #Proper mattrix multiplication

array([[8, 6, 8],
       [6, 5, 7],
       [7, 5, 6]])

In [272]:
ar1+1

array([[3, 2, 3],
       [3, 2, 2],
       [2, 2, 3]])

In [273]:
ar2 *2

array([[2, 2, 4],
       [4, 4, 4],
       [4, 2, 2]])

In [12]:
ar =np.zeros((4,4))

In [13]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
row = np.array([1,2,3,4])

In [14]:
ar+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [15]:
col = np.array([[1,2,3,4]])

In [17]:
ar+col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [18]:
ar*col.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Numpy part two

In [ ]:
# Numpy 